# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title 
auto: true
pygments: true
var:
  archive_path: /archive.html

production_url : http://joshcutler.github.com/PS632-Spring2013/ # or your custom domain name
title : PS632 - Spring 2013

author :
  name : Josh Cutler
  email : josh.cutler@duke.edu
  github : joshcutler
  twitter : josh_cutler
